package ru.bfad.bfaApp.bots.botsApi;

public enum BotState {

    DEFAULT,
    MANAGMENT,
    ASK_INN,

    REGISTRATION,
    REGISTRATION_ASK_FIO,
    REGISTRATION_ASK_PHONE,
    REGISTRATION_ASK_AGENCY,
    END_REGISTRATION,

    GENERAL,
    AUTHORIZATION_CODE,
    ASK_AUTHORIZATION_CODE,
    SHOW_MENU,
    SHOW_REAL_ESTATE_AGENT,

    REAL_ESTATE_AGENT,
    ASK_DATA_FOR_BELONGING,
    ASK_FIO_FOR_BELONGING,
    ASK_PHONENUMBER_FOR_BELONGING,
    BOOKING,
    BOOKING_SELECT_CLIENT,
    PD,
    SCAN_PD,
    SEND_PD,
    SEND_SCAN_PD,
    ASK_OBJECTID,
    ASK_BOOKINGBEFOR,
    SHOWING,
    ASK_SHOWING_DATA,
    ASK_SHOWING_OBJECT,
    SEND_SHOWING,

    IT,
    SHOW_IT,
    WRITE_TO_SUPPORT,
    SEND_MESSAGE_TO_SUPPORT
}
